### PR TITLE
Fix/1291 snackbar group layers

### LINKED ISSUE #1290: Min/max zoom level - Checkboxes do not turn red for group layers when outside zoom level
**Bug deskription for group layers**
When you zoom outside a specified zoom level and switch on a single layer, the checkbox in the layer manager turns red. When you are outside a specified zoom level and switch on a group layer, the checkbox in the layer manager does not turn red.

**Expected behavior and wishes for groups**
That the indicator (red color in checkboxes) that shows that you have zoomed outside a specified zoom level, work the same on group layers as for individual layers. So that red checkboxes is displayed when the layer is lit outside the zoom level.

This is a clarification of the bugs described in #810

### LINKED ISSUE #1291: Min/max zoom level - Snackbar not displayed for layer groups when switched on outside of zoom level
**Bug deskription for group layers**
When you zoom outside of a layers specified zoom level and switch on a normal layer, a snack bar will appear.
When you zoom outside of a layers specified zoom level and switch on a group layer, no snack bar will appear.

**Expected behavior and wishes for group layers**
That the indicators for the layer being turned on outside the specified zoom level, work the same on group layers as for single layers. So that the selected setting for the snackbar is displayed for both group and single layers.

**NOTE**
There are settings in admin for the snackbar - the setting determines if the snackar only should be displayed when the layer is switched on outside the specified zoom lavel, or every time you zoom outside the zoom level when the layer is switched on. Group layers should work like single layers both when this function is activated and deactivated.

This is a clarification of the bugs described in #810 
Related issues: #1290, #1299, #1300.

### PR DESCRIPTION
**Pull request by linusfj**
Closes #1290 and #1291.

### CODE REVIEW

File: new-client/src/plugins/LayerSwitcher/components/LayerGroupItem.js [hunk 1]
```diff
@@ -582,6 +624,26 @@ class LayerGroupItem extends Component {
     );
   };
 
+  showZoomSnack(subLayer) {
+    if (this.zoomWarningSnack) return;
```
Comment (jacobwod) [inline new-client/src/plugins/LayerSwitcher/components/LayerGroupItem.js:628]: Can you expand with some relevant comments? Here is a good place as it might at first seem counter-intuitive (why are we just leaving the method if `zoomWarningSnack` is truthy?).

**Review by jacobwod — COMMENTED** [review]
Which of the proposed solution does this PR implement? We had a couple of ideas, one of them being the "Layer X and n other layers can't be shown". Is it this, or is it more like the other solution in `LayerItem`? 

Btw, does this play well with `LayerItem`'s solution, or will we only get more and more snackbars stacked on each other?

File: new-client/src/plugins/LayerSwitcher/components/LayerGroupItem.js (hunk 1 above)
Comment (linusfj) [reply new-client/src/plugins/LayerSwitcher/components/LayerGroupItem.js:628]: The method ensures that only one `Snackbar` notification is displayed at a time, preventing multiple notifications from overlapping.

**Comment by linusfj** [comment]
> Which of the proposed solution does this PR implement? We had a couple of ideas, one of them being the "Layer X and n other layers can't be shown". Is it this, or is it more like the other solution in `LayerItem`?
> 
> Btw, does this play well with `LayerItem`'s solution, or will we only get more and more snackbars stacked on each other?

In this solution, the messages will stack as they do for `LayerItem`. A suggestion to combine them into one `Snackbar` is described in issue #1300.

**Comment by jacobwod** [comment]
There is some improvement here as we do get the sublayer's name to show. Unfortunately, the behaviour is still far from good UX in my opinion, at least on this setup. I've attached a short video so that you can see what I mean.

My understanding was that this issue would limit the amount of sub-sequential snackbars being display and that's unfortunately not the case as you can see:

https://user-images.githubusercontent.com/110222/234532474-30bb7b9b-9bb9-4068-95c1-a169c2e51011.mov

**Review by jacobwod — CHANGES_REQUESTED** [review]
In addition to the latest video attached, where the functionality does not seem optimal, I have two small issues with this:
- Can you please add some _comments in the code_ as the flow starts getting complex. I see you added a comment to my comment here, but that wasn't what I meant and I'd truly appreciate some comments that explain your thoughts behind the implementation. E.g. compare the amount of comments in the portion above the recently added:
Skärmavbild 2023-04-26 kl  11 33 27
- There's a linter warning about unused variable

Just to be clear: the picture above is just an example, comments are lacking in most places in the new code.

**Comment by linusfj** [comment]
Yes, one of the initial ideas was to limit the number of `Snackbar` messages when turning on a group and include it in this Pull Request, but it has instead been added as issue #1300.

There's also ongoing work in parallel with #1284, where part of the effort is rewriting the layer components. The plan is to continue the development for limiting `Snackbar` messages (#1300) built on top of that code and develop it against a copy of the "1284-add-theme-management" branch. Since the `LayerSwitcher` project is still in progress, those changes will be included in the code delivery after the project has been completed.

Additionally, issues #1290 and #1291 will eventually be adapted for the new layer components in that branch.

In summary, this Pull Request aims to update layer groups (`LayerGroupItem`) to have the same functionality as regular layers (`LayerItem`), despite the presence of some apparent suggestions for improvement.

**Review by jacobwod — APPROVED** [review]
If you've confirmed that:
  - this works both for raster and vector data sources (Hajk's `vectorlayers`)
  - the functionality is as desired
  - there are no compile/lint warnings
  - and **you've successfully merged the _latest_ `develop`**

…then, feel free to merge!
